# Generated by Django 5.1.13 on 2025-11-03 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('anyo_lanzamiento', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Itv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.CharField(choices=[('A', 'Aceptada'), ('P', 'Pendiente'), ('R', 'Rechazada')], max_length=1)),
                ('numero_itv', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mecanico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('antiguedad', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('capacidad', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kilometraje', models.PositiveIntegerField()),
                ('fecha_revision', models.DateField(blank=True, null=True)),
                ('resultado', models.CharField(choices=[('AP', 'Apta'), ('CF', 'Con fallos'), ('GR', 'Grave')], max_length=2)),
                ('coche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisionCoche', to='examen.coche')),
                ('itv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisionItv', to='examen.itv')),
                ('mecanico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisionMecanico', to='examen.mecanico')),
                ('taller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisionTaller', to='examen.taller')),
            ],
        ),
        migrations.AddField(
            model_name='itv',
            name='coches',
            field=models.ManyToManyField(related_name='itvCoche', through='examen.Revision', to='examen.coche'),
        ),
    ]
