# Generated by Django 5.1.13 on 2025-11-02 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('nivel_prioridad', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_revision', models.DateField(blank=True, null=True)),
                ('nombre_tecnico', models.CharField(max_length=150, unique=True)),
                ('resultado', models.CharField(choices=[('CO', 'Correcto'), ('CI', 'Con incidencias'), ('RR', 'Requiere reparación')], max_length=2)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisionAnimal', to='examen.animal')),
            ],
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(blank=True, null=True)),
                ('mensaje', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('P', 'Pendiente'), ('R', 'Resuelta')], default='P', max_length=1)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertaRevision', to='examen.revision')),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipoAnimal', to='examen.tipo'),
        ),
    ]
