# Generated by Django 5.1.13 on 2025-11-01 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movil',
            old_name='usuarios',
            new_name='votos',
        ),
        migrations.AlterField(
            model_name='votar',
            name='movil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votar_movil', to='examen.movil'),
        ),
        migrations.AlterField(
            model_name='votar',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votar_usuario', to='examen.usuario'),
        ),
    ]
